// Images (served statically from public/img/)
export const IMAGES = {
  gun: "/img/gun.png",
  mine: "/img/mine.png",
  slingshot: "/img/slingshot.png",
  mg: "/img/mg.png",
  fog: "/img/fog.png",
  terminator: "/img/terminator.png",
  tiled: "/img/textures/tiled.png",
  guided: "/img/guided.png",
  grenade: "/img/grenade.png",
  wallBuilder: "/img/wallBuilder.png",
  speed: "/img/speed.png",
  laser: "/img/laser.png",
  multi: "/img/multi.png",
  wreckingBall: "/img/wreckingBall.png",
  invincible: "/img/invincible.png",
};

// Sounds (served statically from public/sound/)
export const SOUNDS = {
  reload: "/sound/reload.wav",
  gun: "/sound/gun.wav",
  gamestart: "/sound/gamestart.wav",
  flag: "/sound/flag.wav",
  killingspree: "/sound/killingspree.mp3",
  grenade: "/sound/grenade.wav",
  invincible: "/sound/invincible.mp3",
  powerup: "/sound/powerup.wav",
  bounce: "/sound/bounce.wav",
  laser: "/sound/laser.wav",
  resetFlag: "/sound/resetFlag.wav",
  mg: "/sound/mg.wav",
  fanfare: "/sound/fanfare.mp3",
  kill: "/sound/kill.wav",
  guided: "/sound/guided.wav",
  coin: "/sound/coin.wav",
  origPowerup: "/sound/original/powerup.mp3",
  origLaser: "/sound/original/laser.mp3",
  origGun: "/sound/original/gun.mp3",
  terminator: "/sound/terminator.mp3",
};
